### ISSUE TITLE
Use of usize instead of i32 for dimensions/lengths?

### ISSUE THREAD

**Issue by JP-Ellis** [mikkyang/rust-blas#10]
I was curious as to whether there was any reason for using `i32` instead of `usize` for various 'size' parameters?  Are negative integers ever returned?  And what if (hypothetically speaking) a Vector on a 64-bit machine has a length exceeding the maximum i32 integer?

I'll have a go at implementing this change, but it will unfortunately break quite a lot of function (though easily fixable, and better late than never).

**Comment by mikkyang** [comment]
Originally I had used `u32` instead of `i32`, but the C headers all used `i32` and I wasn't certain of the behavior for numbers that are beyond the range of positive numbers of `i32`, but within `u32` (which would represent the negative numbers in `i32`). Because of this, I wanted the user or whoever that implemented the trait to perform this check by themselves (hence the use of NumCast in implementing such trait methods for Vec) and make this behavior transparent.

I've yet to investigate what the actual behavior for such input is, so it could be possible that the above conjecture is all for nought, but I wanted to be on the safe side before changing everything.

**Comment by JP-Ellis** [comment]
Yeh, if it arises from the C headers, I guess not all that much can be done.  I doubt there would ever be a context where one would use more than 2^31 elements.  Also, having a quick look at casting `usize` to `i32`, it doesn't seem to raise any warning and we just have that `u64::MAX as i32` and `u32::MAX as i32` both equal `-1`.
